<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Structs.cs" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Structs.cs" Link="Structs.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="StbImageSharp" Version="2.30.15" />
  </ItemGroup>

</Project>
